### ISSUE TITLE
Security Issue Report

### ISSUE THREAD

**Issue by Th1s** [apache/shardingsphere-ui#70]
Hi, 

I have found 2 critical security issues in ShardingSphere UI 4.1.1 and sent a email to security@apache.org with issue details by this email (jincsheng@gmail.com) . 

But three days passed, I have not received a reply email.

So do you already know the details of theses issues? And what is the next step?

**Comment by terrymanu** [comment]
Hi, security issue cannot discuss in public area, I will try to delete this issue.
